### PR TITLE
Add argument to use regex library

### PR DESCRIPTION
**Pull request by rominf**

### CODE REVIEW

**Comment by rominf** [comment]
I don't understand why `regex` library cannot be imported (I install it before with `pip`). @erikrose, can you look at this?

**Comment by erikrose** [comment]
You're installing it into the global environment. Tox then creates a fresh environment for each version of Python it tests against. You'd need to add regex to tox.ini.

Also, can you describe the intent of your PR?

**Comment by rominf** [comment]
@erikrose, there are many features that exist only in `regex` module. For a full list refer to https://pypi.org/project/regex/.
Will you merge this PR if I fix the tests?

**Comment by erikrose** [comment]
I think I’d rather keep Parsimonious simple. Eventually, I want to evolve it away from explicitly having regexes as a language feature and either cease to expose them or compile them down to simple operations as in the original PEG paper. Thanks for the idea, though; regex looks like a neat lib.

**Pull request closed without merging**
