### PR TITLE
Remove some redundant code in Sequence expression

### PR DESCRIPTION
**Pull request by zhuzilin**
Thank you for your time on reviewing this PR.

### CODE REVIEW

**Review by evanh — APPROVED** [review]
Nice!

**Review by lonnen — APPROVED** [review]
🎆

**Comment by lonnen** [comment]
@zhuzilin thanks for the contribution! I didn't see this before the candidate for `0.9.0` but I'll land this shortly after that is published

**Comment by lucaswiman** [comment]
I don't see much impact on benchmarks, but this is a nice simplification.

**Comment by lucaswiman** [comment]
I don't see much impact on benchmarks, but this is a nice simplification.

**Pull request merged**
