### PR TITLE
Combine

### PR DESCRIPTION
**Pull request by righthandabacus**
Try to simplify (kind-of) some grammar expressions and introduce range expressions (issue #139)

### CODE REVIEW

**Comment by erikrose** [comment]
This looks interesting. Added to my review queue. Thanks!

**Comment by righthandabacus** [comment]
merge master to this PR, so get rid of the failed check due to Py3.3

**Comment by lucaswiman** [comment]
I'm going to work on combining this with my PR #203, which makes some similar though not identical changes, then getting the result merged.

**Comment by lucaswiman** [comment]
These commits were included in #203, though rebased, so merging it did not close this PR. This should go out in the next version of parsimonious.

**Pull request closed without merging**
